import { useState, useEffect, useRef } from "react";

// ── Mermaid ───────────────────────────────────────────────────
const loadMermaid = () => new Promise(resolve => {
  if (window.mermaid) return resolve(window.mermaid);
  const s = document.createElement("script");
  s.src = "https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.min.js";
  s.onload = () => {
    window.mermaid.initialize({
      startOnLoad: false, theme: "base",
      themeVariables: {
        primaryColor:"#0F2D5C", primaryTextColor:"#C8DEFF",
        primaryBorderColor:"#1E4A8C", lineColor:"#3A7FD5",
        secondaryColor:"#071828", background:"#050E1A",
        mainBkg:"#0F2D5C", nodeBorder:"#1E4A8C",
        edgeLabelBackground:"#071828",
        fontFamily:"JetBrains Mono, monospace", fontSize:"12px",
      },
    });
    resolve(window.mermaid);
  };
  document.head.appendChild(s);
});

// ── Spreadsheet → workflow JSON ───────────────────────────────
const sheetToWorkflow = (sheet) => ({
  name: sheet.name,
  description: sheet.description,
  states:      sheet.states.filter(r => r.name.trim()),
  transitions: sheet.transitions.filter(r => r.from.trim() && r.to.trim()),
  users:       sheet.users.filter(r => r.name.trim()),
  properties:  sheet.properties.filter(r => r.name.trim()),
  rules:       sheet.rules.filter(r => r.text.trim()).map(r => r.text),
});

// ── Workflow → Mermaid ────────────────────────────────────────
const toMermaid = (wf) => {
  if (!wf.states.length) return null;
  let d = "stateDiagram-v2\n";
  wf.states.forEach(s => {
    if (s.initial) d += `  [*] --> ${s.id || s.name.replace(/\s+/g,"_")}\n`;
    const id = s.id || s.name.replace(/\s+/g,"_").replace(/[^a-zA-Z0-9_]/g,"");
    if (s.name !== id) d += `  ${id} : ${s.name}\n`;
  });
  wf.transitions.forEach(t => {
    const f = t.from.replace(/\s+/g,"_").replace(/[^a-zA-Z0-9_]/g,"");
    const to = t.to.replace(/\s+/g,"_").replace(/[^a-zA-Z0-9_]/g,"");
    d += `  ${f} --> ${to}\n`;
  });
  return d;
};

// ── PRD generator ─────────────────────────────────────────────
const generatePRD = (wf) => {
  const today = new Date().toLocaleDateString("en-CA");
  const name = wf.name || "Unnamed Project";
  let p = `# ${name}\n## Product Requirements Document\n\n---\n\n`;
  p += `| Field | Detail |\n| :--- | :--- |\n`;
  p += `| **Project** | ${name} |\n| **Generated** | ${today} |\n| **Source** | Proviso SOW Spreadsheet |\n\n---\n\n`;
  p += `## 1. Overview\n\n${wf.description || `Auto-generated PRD for ${name}.`}\n\n---\n\n`;
  if (wf.users.length) {
    p += `## 2. Users and Roles\n\n| Name | Role | Email | Contract Manager |\n| :--- | :--- | :--- | :--- |\n`;
    wf.users.forEach(u => { p += `| ${u.name} | ${u.role||"—"} | ${u.email||"—"} | ${u.isCM?"Yes":"No"} |\n`; });
    p += "\n---\n\n";
  }
  const s = wf.users.length ? 3 : 2;
  p += `## ${s}. Workflow — ${name}\n\n`;
  p += `### States\n\n| State | Initial |\n| :--- | :--- |\n`;
  wf.states.forEach(st => { p += `| ${st.name} | ${st.initial?"Yes":"No"} |\n`; });
  p += `\n### Transitions\n\n| From | To |\n| :--- | :--- |\n`;
  wf.transitions.forEach(t => { p += `| ${t.from} | ${t.to} |\n`; });
  if (wf.properties.length) {
    p += `\n---\n\n## ${s+1}. Properties\n\n| Field | Type | Required |\n| :--- | :--- | :--- |\n`;
    wf.properties.forEach(pr => { p += `| ${pr.name} | ${pr.type||"Text"} | ${pr.required?"Yes":"No"} |\n`; });
  }
  if (wf.rules.length) {
    p += `\n---\n\n## ${s+2}. Business Rules\n\n`;
    wf.rules.forEach((r,i) => { p += `${i+1}. ${r}\n`; });
  }
  p += `\n---\n\n## ${s+3}. Test Cases\n\n| # | Test | Type |\n| :- | :--- | :--- |\n`;
  let tc=1;
  wf.transitions.slice(0,8).forEach(t => { p += `| T${tc++} | ${t.from} → ${t.to} | Workflow |\n`; });
  wf.rules.slice(0,4).forEach(r => { p += `| T${tc++} | ${r.slice(0,60)} | Business rule |\n`; });
  const hrs = wf.states.length*3 + wf.transitions.length + wf.properties.length*2 + 25;
  p += `\n---\n\n## ${s+4}. Build Estimate\n\n`;
  p += `| Phase | Hours |\n| :--- | :--- |\n`;
  p += `| Schema + Parser | 15–20 |\n`;
  p += `| COM Provisioner (${wf.states.length} states) | ${hrs-15}–${Math.round((hrs-15)*1.3)} |\n`;
  p += `| Test Runner | 10–15 |\n`;
  p += `| **Total** | **${hrs}–${Math.round(hrs*1.3)}** |\n\n`;
  p += `---\n\n*Generated by Proviso · scriptdotnet © ${new Date().getFullYear()}*\n`;
  return p;
};

// ── Default spreadsheet data ──────────────────────────────────
const DEFAULT_SHEET = {
  name: "Contract Lifecycle",
  description: "Acme Corporation contract management — Service Agreements and NDAs.",
  states: [
    { name:"Draft",              initial:true  },
    { name:"Under Review",       initial:false },
    { name:"Reviewed",           initial:false },
    { name:"Approve 50k",        initial:false },
    { name:"Approve High",       initial:false },
    { name:"Signed Internally",  initial:false },
    { name:"Sent to Customer",   initial:false },
    { name:"Signed by Customer", initial:false },
    { name:"About to Expire",    initial:false },
    { name:"Expired",            initial:false },
    { name:"Discarded",          initial:false },
  ],
  transitions: [
    { from:"Draft",              to:"Under Review"       },
    { from:"Under Review",       to:"Reviewed"           },
    { from:"Under Review",       to:"Draft"              },
    { from:"Reviewed",           to:"Approve 50k"        },
    { from:"Reviewed",           to:"Approve High"       },
    { from:"Approve 50k",        to:"Signed Internally"  },
    { from:"Approve High",       to:"Signed Internally"  },
    { from:"Signed Internally",  to:"Sent to Customer"   },
    { from:"Sent to Customer",   to:"Signed by Customer" },
    { from:"Signed by Customer", to:"About to Expire"    },
    { from:"About to Expire",    to:"Expired"            },
    { from:"Draft",              to:"Discarded"          },
    { from:"Under Review",       to:"Discarded"          },
    { from:"Reviewed",           to:"Discarded"          },
    { from:"Discarded",          to:"Draft"              },
  ],
  users: [
    { name:"Bill Ward",      role:"CEO",              email:"bill.ward@acme.com",           isCM:true  },
    { name:"Betty Black",    role:"CFO",              email:"betty.black@acme.com",         isCM:true  },
    { name:"Molly Chambers", role:"Sales Director",   email:"molly.chambers@acme.com",      isCM:true  },
    { name:"Raymond Oakley", role:"Sales Engineer",   email:"raymond.oakley@acme.com",      isCM:false },
    { name:"Tom McKenzie",   role:"Service Manager",  email:"tom.mckenzie@acme.com",        isCM:false },
  ],
  properties: [
    { name:"Contract Title",  type:"Text",    required:true  },
    { name:"Contract Number", type:"Integer", required:true  },
    { name:"Contract Value",  type:"Decimal", required:true  },
    { name:"Customer",        type:"Lookup",  required:true  },
    { name:"Contract Owner",  type:"Lookup",  required:true  },
    { name:"Effective Date",  type:"Date",    required:false },
    { name:"Expiration Date", type:"Date",    required:false },
  ],
  rules: [
    { text:"Service Agreements over 50,000 euros require Executive Management approval" },
    { text:"Only Contract Managers can create and edit contracts" },
    { text:"All users can view all contracts at all times" },
    { text:"Signed contracts are converted to PDF and locked from editing" },
  ],
};

// ── JSON renderer ─────────────────────────────────────────────
function JV({ data }) {
  const r = (v,d=0) => {
    const p="  ".repeat(d);
    if(v===null) return <span style={{color:"#475569"}}>null</span>;
    if(typeof v==="boolean") return <span style={{color:"#FBBF24"}}>{String(v)}</span>;
    if(typeof v==="number")  return <span style={{color:"#FB923C"}}>{v}</span>;
    if(typeof v==="string")  return <span style={{color:"#4ADE80"}}>"{v}"</span>;
    if(Array.isArray(v))     return !v.length?<span>[]</span>:(
      <span>{"[\n"}{v.map((x,i)=><span key={i}>{p}{"  "}{r(x,d+1)}{i<v.length-1?",":""}{"\n"}</span>)}{p}{"]"}</span>
    );
    const ks=Object.keys(v);
    return <span>{"{\n"}{ks.map((k,i)=>(
      <span key={k}>{p}{"  "}<span style={{color:"#5BA4F5"}}>"{k}"</span>{": "}{r(v[k],d+1)}{i<ks.length-1?",":""}{"\n"}</span>
    ))}{p}{"}"}</span>;
  };
  return <pre style={{fontFamily:"JetBrains Mono,monospace",fontSize:10.5,lineHeight:1.8,color:"#C8DEFF"}}>{r(data)}</pre>;
}

// ── Markdown renderer ─────────────────────────────────────────
function MD({ src }) {
  const lines = src.split("\n");
  const els=[]; let key=0, tRows=[], inT=false;
  const flushT=()=>{
    if(!tRows.length)return;
    const rows=tRows.map(r=>r.split("|").map(c=>c.trim()).filter(Boolean));
    els.push(<table key={key++} style={{width:"100%",borderCollapse:"collapse",fontSize:11,marginBottom:12}}>
      <thead><tr>{rows[0].map((c,i)=><th key={i} style={{background:"#0E2038",color:"#5878A0",padding:"6px 10px",textAlign:"left",fontWeight:500,fontSize:10,borderBottom:"1px solid #162C4A"}}>{c}</th>)}</tr></thead>
      <tbody>{rows.slice(1).map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} style={{padding:"6px 10px",borderBottom:"1px solid rgba(22,44,74,.5)",color:"#C8DEFF",lineHeight:1.5}}>{c}</td>)}</tr>)}</tbody>
    </table>);
    tRows=[]; inT=false;
  };
  const fmt=t=>{
    t=t.replace(/\*\*(.+?)\*\*/g,"<b>$1</b>").replace(/\*(.+?)\*/g,"<i>$1</i>").replace(/`(.+?)`/g,"<code style='background:#0E2038;padding:1px 5px;border-radius:3px;font-size:10px'>$1</code>");
    return <span dangerouslySetInnerHTML={{__html:t}}/>;
  };
  for(const raw of lines){
    const l=raw.trim();
    if(l.startsWith("|")){if(/^\|[\s\-:|]+\|/.test(l))continue;inT=true;tRows.push(l);continue;}
    if(inT)flushT();
    if(!l){els.push(<div key={key++} style={{height:8}}/>);continue;}
    if(/^---+$/.test(l)){els.push(<hr key={key++} style={{border:"none",borderTop:"1px solid #162C4A",margin:"14px 0"}}/>);continue;}
    if(l.startsWith("# "))  {els.push(<div key={key++} style={{fontFamily:"Fraunces,serif",fontSize:18,fontWeight:700,color:"#fff",marginBottom:6}}>{l.slice(2)}</div>);continue;}
    if(l.startsWith("## ")) {els.push(<div key={key++} style={{fontFamily:"Fraunces,serif",fontSize:14,fontWeight:600,color:"#4A9FFF",margin:"18px 0 8px",paddingBottom:4,borderBottom:"1px solid #162C4A"}}>{l.slice(3)}</div>);continue;}
    if(l.startsWith("### ")){els.push(<div key={key++} style={{fontSize:12,fontWeight:600,color:"#C8DEFF",margin:"12px 0 5px"}}>{l.slice(4)}</div>);continue;}
    if(/^\d+\.\s/.test(l)||l.startsWith("- ")){els.push(<div key={key++} style={{fontSize:11.5,color:"#5878A0",paddingLeft:14,position:"relative",marginBottom:3,lineHeight:1.6}}><span style={{position:"absolute",left:0,color:"#4A9FFF"}}>›</span>{fmt(l.replace(/^[\d]+\.\s|^-\s/,""))}</div>);continue;}
    els.push(<div key={key++} style={{fontSize:11.5,color:"#5878A0",marginBottom:6,lineHeight:1.7}}>{fmt(l)}</div>);
  }
  if(inT)flushT();
  return <div>{els}</div>;
}

// ── CSS ───────────────────────────────────────────────────────
const CSS = `
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,300;0,400;0,500;1,400&family=Fraunces:ital,wght@0,400;0,600;0,700;1,400&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --bg:#030910;--s1:#07111F;--s2:#0A1828;--s3:#0E2038;--s4:#142848;
  --border:#162C4A;--bdr2:#1E3D60;
  --accent:#1565D8;--a2:#2478F0;--a3:#4A9FFF;
  --green:#00C870;--red:#FF3D5A;--gold:#F0A500;--purple:#7C5CFC;
  --text:#C8DCFF;--mid:#5878A0;--dim:#243A58;
  --mono:'JetBrains Mono',monospace;--display:'Fraunces',serif;
}
html,body{height:100%;overflow:hidden}
body{background:var(--bg);color:var(--text);font-family:var(--mono);font-size:13px}

.shell{display:flex;height:100vh}

/* Sidebar */
.sb{width:196px;flex-shrink:0;background:var(--s1);border-right:1px solid var(--border);display:flex;flex-direction:column}
.sb-logo{padding:20px 16px 16px;border-bottom:1px solid var(--border)}
.sb-wm{font-family:var(--display);font-size:22px;font-weight:700;color:#fff;letter-spacing:-.5px;line-height:1}
.sb-wm em{color:var(--a3);font-style:normal}
.sb-tag{font-size:9px;color:var(--dim);letter-spacing:1.4px;text-transform:uppercase;margin-top:5px}
.sb-nav{flex:1;padding:10px 0}
.sb-item{display:flex;align-items:center;gap:10px;padding:10px 16px;cursor:pointer;border-left:3px solid transparent;transition:all .15s}
.sb-item:hover{background:rgba(21,101,216,.07)}
.sb-item.active{background:rgba(21,101,216,.1);border-left-color:var(--a3)}
.sb-num{width:20px;height:20px;border-radius:5px;flex-shrink:0;background:var(--s3);border:1px solid var(--border);font-size:10px;color:var(--dim);display:flex;align-items:center;justify-content:center;transition:all .15s}
.sb-item.active .sb-num{background:var(--accent);border-color:var(--a2);color:#fff}
.sb-item.done .sb-num{background:rgba(0,200,112,.12);border-color:var(--green);color:var(--green)}
.sb-lbl{font-size:11px;color:var(--mid);transition:color .15s;line-height:1.3}
.sb-sub{font-size:9px;color:var(--dim);margin-top:1px}
.sb-item:hover .sb-lbl,.sb-item.active .sb-lbl{color:var(--text)}
.sb-foot{padding:12px 16px;border-top:1px solid var(--border);font-size:9px;color:var(--dim);line-height:1.9}
.dot{display:inline-block;width:5px;height:5px;border-radius:50%;background:var(--dim);margin-right:5px;vertical-align:middle;transition:background .2s}
.dot.on{background:var(--green)}

/* ── Custom Tooltip ── */
.tip-wrap{position:relative;display:inline-flex;align-items:center}
.tip-box{
  position:absolute;
  left:calc(100% + 10px);
  top:50%;transform:translateY(-50%);
  background:#0A1828;
  border:1px solid var(--a3);
  border-radius:6px;
  padding:7px 11px;
  font-family:var(--mono);
  font-size:10px;
  color:var(--a3);
  white-space:nowrap;
  pointer-events:none;
  opacity:0;
  transform:translateY(-50%) translateX(4px);
  transition:opacity .18s ease, transform .18s ease;
  z-index:999;
  box-shadow:0 4px 16px rgba(0,0,0,.5), 0 0 0 1px rgba(74,159,255,.08);
}
.tip-box::before{
  content:'';
  position:absolute;
  right:100%;top:50%;transform:translateY(-50%);
  border:5px solid transparent;
  border-right-color:var(--a3);
}
.tip-box::after{
  content:'';
  position:absolute;
  right:calc(100% + 1px);top:50%;transform:translateY(-50%);
  border:5px solid transparent;
  border-right-color:#0A1828;
}
.tip-wrap:hover .tip-box{
  opacity:1;
  transform:translateY(-50%) translateX(0);
}
/* Tooltip above — for the Generate PRD button (tooltip appears above) */
.tip-box.above{
  left:50%;top:auto;bottom:calc(100% + 8px);
  transform:translateX(-50%) translateY(-4px);
}
.tip-box.above::before{
  right:auto;left:50%;top:100%;
  transform:translateX(-50%);
  border:5px solid transparent;
  border-top-color:var(--a3);
}
.tip-box.above::after{
  right:auto;left:50%;top:calc(100% + 1px);
  transform:translateX(-50%);
  border:5px solid transparent;
  border-top-color:#0A1828;
}
.tip-wrap:hover .tip-box.above{
  transform:translateX(-50%) translateY(0);
}
/* Tooltip icon dot */
.tip-dot{
  width:5px;height:5px;border-radius:50%;
  background:var(--a3);opacity:.5;
  margin-left:5px;flex-shrink:0;
  animation:tip-pulse 2s ease-in-out infinite;
}
@keyframes tip-pulse{0%,100%{opacity:.2}50%{opacity:.8}}
.main{flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0}
.topbar{height:44px;flex-shrink:0;background:var(--s1);border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 18px;gap:10px}
.tb-title{font-family:var(--display);font-size:13px;font-weight:600;color:var(--text);flex:1;letter-spacing:-.2px}
.tb-pill{font-size:9px;font-family:var(--mono);background:rgba(21,101,216,.1);border:1px solid rgba(21,101,216,.2);color:var(--a3);padding:3px 8px;border-radius:20px;letter-spacing:.5px}
.tb-pill.ai{background:rgba(124,92,252,.1);border-color:rgba(124,92,252,.25);color:#A78BFA}
.content{flex:1;overflow:hidden;display:flex;flex-direction:column}

/* ── SPREADSHEET SCREEN ── */
.ss-screen{flex:1;display:grid;grid-template-columns:1fr 1fr;overflow:hidden}
.ss-left{display:flex;flex-direction:column;overflow:hidden;border-right:1px solid var(--border)}
.ss-head{padding:8px 12px;background:var(--s2);border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;flex-shrink:0}
.ss-headlbl{font-size:9px;font-weight:600;color:var(--mid);letter-spacing:.8px;text-transform:uppercase}
.ss-acts{display:flex;gap:5px;align-items:center}
.xb{font-size:9.5px;font-family:var(--mono);padding:3px 8px;border-radius:3px;border:1px solid var(--border);background:transparent;color:var(--mid);cursor:pointer;transition:all .15s;white-space:nowrap}
.xb:hover{border-color:var(--a2);color:var(--a3)}
.xb.blue{background:var(--accent);border-color:var(--accent);color:#fff}
.xb.blue:hover{background:var(--a2)}
.xb.green{background:rgba(0,200,112,.12);border-color:var(--green);color:var(--green)}
.xb.red{background:rgba(255,61,90,.1);border-color:var(--red);color:var(--red)}
.xb:disabled{opacity:.35;cursor:not-allowed}

/* Spreadsheet body */
.sheet-body{flex:1;overflow-y:auto;background:var(--bg)}

/* Section */
.sec{border-bottom:1px solid var(--border)}
.sec-header{
  display:flex;align-items:center;gap:8px;
  padding:8px 12px;background:var(--s2);
  cursor:pointer;user-select:none;
  border-bottom:1px solid var(--border);
  position:sticky;top:0;z-index:2;
}
.sec-chevron{font-size:10px;color:var(--mid);transition:transform .15s;flex-shrink:0}
.sec-chevron.open{transform:rotate(90deg)}
.sec-title{font-size:10px;font-weight:700;color:var(--text);letter-spacing:.3px;flex:1}
.sec-count{font-size:9px;color:var(--dim);font-family:var(--mono)}
.sec-add{font-size:9px;padding:2px 7px;border-radius:3px;border:1px solid var(--border);background:transparent;color:var(--mid);cursor:pointer;transition:all .15s;font-family:var(--mono)}
.sec-add:hover{border-color:var(--green);color:var(--green)}

/* Project name row */
.proj-row{padding:10px 12px;border-bottom:1px solid var(--border);display:grid;grid-template-columns:90px 1fr;gap:0;align-items:center}
.proj-label{font-size:9px;color:var(--mid);letter-spacing:.5px;text-transform:uppercase}
.proj-input{background:transparent;border:none;outline:none;font-family:var(--mono);font-size:12px;color:var(--text);width:100%;padding:2px 6px}
.proj-input:focus{background:var(--s3);border-radius:3px}
.proj-input::placeholder{color:var(--dim)}

/* Table grid */
.sheet-table{width:100%;border-collapse:collapse}
.sheet-table thead tr{background:var(--s3)}
.sheet-table thead th{
  padding:6px 8px;font-size:9px;font-weight:600;
  color:var(--dim);letter-spacing:.8px;text-transform:uppercase;
  text-align:left;border-bottom:1px solid var(--border);
  border-right:1px solid var(--border);white-space:nowrap;
}
.sheet-table thead th:last-child{border-right:none}
.sheet-table tbody tr{transition:background .1s}
.sheet-table tbody tr:hover{background:rgba(21,101,216,.04)}
.sheet-table tbody td{
  padding:0;border-bottom:1px solid rgba(22,44,74,.5);
  border-right:1px solid rgba(22,44,74,.4);
  vertical-align:middle;
}
.sheet-table tbody td:last-child{border-right:none}

/* Cell input */
.cell-input{
  display:block;width:100%;
  background:transparent;border:none;outline:none;
  font-family:var(--mono);font-size:11px;color:var(--text);
  padding:6px 8px;line-height:1.4;
  transition:background .1s;
}
.cell-input:focus{background:var(--s3);outline:1px solid var(--accent)}
.cell-input::placeholder{color:var(--dim)}

/* Checkbox cell */
.cell-check{display:flex;align-items:center;justify-content:center;padding:6px}
.cell-check input[type=checkbox]{
  width:13px;height:13px;cursor:pointer;accent-color:var(--accent);
}

/* Select cell */
.cell-select{
  display:block;width:100%;
  background:transparent;border:none;outline:none;
  font-family:var(--mono);font-size:11px;color:var(--text);
  padding:6px 8px;cursor:pointer;
}
.cell-select:focus{background:var(--s3)}

/* Selected row */
.sheet-table tbody tr.selected{background:rgba(21,101,216,.12) !important}
.sheet-table tbody tr.selected td{border-bottom:1px solid rgba(21,101,216,.25)}
.sheet-table tbody tr.selected .cell-input{color:#fff}
.row-sel-bar{
  display:block;width:3px;height:100%;
  background:var(--a3);border-radius:2px;
  flex-shrink:0;
}
.row-idx{
  font-size:9px;color:var(--dim);
  width:20px;text-align:center;
  flex-shrink:0;user-select:none;
}
tr.selected .row-idx{color:var(--a3);font-weight:700}

/* Diagram node pulse when row selected */
@keyframes node-pulse{
  0%  {filter:drop-shadow(0 0 0px rgba(74,159,255,0))}
  40% {filter:drop-shadow(0 0 8px rgba(74,159,255,.9))}
  100%{filter:drop-shadow(0 0 0px rgba(74,159,255,0))}
}
.diagram-pulse svg .node.selected-node rect,
.diagram-pulse svg .node.selected-node circle{
  stroke:#4A9FFF !important;
  stroke-width:2.5px !important;
}
.selected-node-wrap{animation:node-pulse .8s ease-out 1}

/* Outgoing transitions badge on selected row */
.trans-badges{
  display:flex;gap:4px;flex-wrap:wrap;
  padding:3px 6px;
}
.trans-badge{
  font-size:9px;
  background:rgba(74,159,255,.1);
  border:1px solid rgba(74,159,255,.2);
  color:var(--a3);
  padding:1px 6px;border-radius:10px;
  white-space:nowrap;
}
  background:transparent;border:none;cursor:pointer;
  color:var(--dim);font-size:11px;padding:4px 6px;
  transition:color .15s;line-height:1;
}
.del-btn:hover{color:var(--red)}

/* ── RIGHT PANE (diagram / json) ── */
.ss-right{display:flex;flex-direction:column;overflow:hidden;background:var(--s1)}
.d-head{padding:8px 12px;background:var(--s2);border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;flex-shrink:0}
.d-body{flex:1;overflow:auto;display:flex;align-items:flex-start;justify-content:center;padding:18px}
.d-body svg{max-width:100%;height:auto}
.d-empty{display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;color:var(--dim);font-size:11px;gap:8px;text-align:center;line-height:1.7}
.d-empty-icon{font-size:32px;opacity:.2;margin-bottom:4px}
.tab-row{display:flex;gap:2px}
.tab{font-size:9.5px;padding:3px 8px;border-radius:3px;border:1px solid transparent;background:transparent;color:var(--dim);cursor:pointer;transition:all .15s;font-family:var(--mono)}
.tab:hover{color:var(--text)}
.tab.on{background:var(--s3);border-color:var(--border);color:var(--text)}
.json-body{flex:1;overflow:auto;padding:14px 16px;font-size:10.5px;line-height:1.8}

/* Nav arrows hint */
.nav-hint{
  display:flex;align-items:center;gap:6px;
  font-size:10px;color:var(--mid);
  background:var(--s3);border:1px solid var(--border);
  border-radius:4px;padding:3px 8px;
}
.nav-hint-arrow{
  display:flex;flex-direction:column;gap:1px;
}
.nav-arrow{
  font-size:9px;line-height:1;cursor:pointer;
  transition:color .15s;padding:0 1px;
}
.nav-arrow:hover{color:var(--a3)}
.nav-arrow.active{color:var(--a3)}

/* ── PRD SCREEN ── */
.prd-screen{flex:1;display:grid;grid-template-columns:1fr 1fr;overflow:hidden}
.prd-left{display:flex;flex-direction:column;overflow:hidden;border-right:1px solid var(--border)}
.prd-preview{flex:1;overflow:auto;padding:18px 22px;font-size:12px;line-height:1.8;color:var(--text)}
.prd-empty{display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;color:var(--dim);font-size:11px;gap:12px;text-align:center;line-height:1.7;position:relative}
.prd-empty-icon{font-size:36px;opacity:.2;margin-bottom:4px}

/* Hint — no hand, just pulsing ring + label */
.hint-wrap{display:flex;flex-direction:column;align-items:center;gap:12px;margin-top:8px}
.hint-ring-wrap{position:relative;display:flex;align-items:center;justify-content:center;width:52px;height:52px}
.hint-ring{width:48px;height:48px;border-radius:50%;border:1.5px solid rgba(74,159,255,.3);position:absolute;animation:ring-pulse 1.8s ease-out infinite;pointer-events:none}
.hint-ring:nth-child(2){animation-delay:.6s}
.hint-ring:nth-child(3){animation-delay:1.2s}
@keyframes ring-pulse{0%{transform:scale(.6);opacity:.8}100%{transform:scale(2.2);opacity:0}}
.hint-label-row{display:flex;align-items:center;gap:8px;animation:hint-slide .9s ease-in-out infinite}
@keyframes hint-slide{0%,100%{transform:translateX(0)}50%{transform:translateX(8px)}}
.hint-arrow-txt{font-size:13px;color:var(--a3)}
.hint-lbl{font-size:12px;font-weight:600;color:var(--a3);letter-spacing:.3px}
.hint-sub{font-size:10px;color:var(--mid);animation:hint-fade 1.8s ease-in-out infinite}
@keyframes hint-fade{0%,100%{opacity:.5}50%{opacity:1}}

/* Generate btn pulse */
.xb.blue.prd-btn{position:relative;overflow:visible}
.xb.blue.prd-btn::after{content:'';position:absolute;inset:-3px;border-radius:5px;border:1px solid rgba(74,159,255,.4);animation:btn-glow 1.6s ease-in-out infinite;pointer-events:none}
@keyframes btn-glow{0%,100%{opacity:0;transform:scale(1)}50%{opacity:1;transform:scale(1.04)}}

/* Mode cards */
.mode-cards{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:14px}
.mode-card{border-radius:6px;padding:10px 12px;transition:all .2s;cursor:pointer}
.mode-card.nlp{background:rgba(21,101,216,.08);border:1px solid rgba(21,101,216,.3)}
.mode-card.ai{background:rgba(124,92,252,.08);border:1px solid rgba(124,92,252,.3)}
.mode-card.inactive{opacity:.3;filter:grayscale(.5)}
.mode-card-title{font-size:9px;font-weight:700;letter-spacing:1px;text-transform:uppercase;margin-bottom:5px;display:flex;align-items:center;gap:5px}
.mode-card.nlp .mode-card-title{color:var(--a3)}
.mode-card.ai  .mode-card-title{color:#A78BFA}
.mode-active-badge{font-size:8px;background:var(--accent);color:#fff;padding:1px 5px;border-radius:2px;letter-spacing:0}
.mode-card.ai .mode-active-badge{background:#7C5CFC}
.mode-card-body{font-size:9.5px;color:var(--mid);line-height:1.6}

/* ── INGEST SCREEN ── */
.ingest-screen{flex:1;overflow-y:auto;padding:22px 28px;display:flex;flex-direction:column;gap:16px}
.card{background:var(--s1);border:1px solid var(--border);border-radius:8px;overflow:hidden}
.card-head{padding:10px 16px;background:var(--s2);border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between}
.card-title{font-size:9px;font-weight:500;color:var(--mid);letter-spacing:1px;text-transform:uppercase}
.card-body{padding:16px}
.fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}
.ff{grid-column:1/-1}
.fl{display:block;font-size:8.5px;color:var(--mid);letter-spacing:1px;text-transform:uppercase;margin-bottom:4px}
.fi{width:100%;background:var(--bg);border:1px solid var(--border);border-radius:4px;padding:8px 10px;font-family:var(--mono);font-size:11px;color:var(--text);outline:none;transition:border-color .15s}
.fi:focus{border-color:var(--a2)}
.fi:disabled{opacity:.4}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}
.stat{background:var(--s1);border:1px solid var(--border);border-radius:6px;padding:12px 14px;text-align:center}
.sv{font-family:var(--display);font-size:24px;font-weight:700;color:var(--a3);line-height:1;margin-bottom:3px}
.sv.off{color:var(--dim)}
.sl{font-size:8.5px;color:var(--mid);letter-spacing:.5px}
.big-btn{width:100%;padding:13px;border:none;border-radius:6px;font-family:var(--mono);font-size:11.5px;font-weight:600;cursor:pointer;transition:all .15s;display:flex;align-items:center;justify-content:center;gap:8px;background:var(--accent);color:#fff}
.big-btn:hover{background:var(--a2);transform:translateY(-1px)}
.big-btn:disabled{opacity:.3;cursor:not-allowed;transform:none}
.big-btn.done{background:rgba(0,200,112,.15);border:1px solid var(--green);color:var(--green)}
.log{background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:12px 14px;min-height:130px;max-height:200px;overflow-y:auto;font-size:10.5px;line-height:2}
.ll{display:flex;gap:8px}
.lt{color:var(--dim);flex-shrink:0;font-size:9.5px}
.lok{color:var(--green)}.linf{color:var(--a3)}.lwarn{color:var(--gold)}.lerr{color:var(--red)}
.result-row{background:var(--s1);border:1px solid var(--border);border-radius:8px;padding:16px 18px;display:flex;align-items:center;gap:14px}
.ri{font-size:22px;flex-shrink:0}
.rt{font-family:var(--display);font-size:13px;font-weight:600;color:#fff}
.rs{font-size:10px;color:var(--mid);margin-top:2px}
.rp{margin-left:auto;font-size:9.5px;text-align:center;line-height:1.7;background:rgba(21,101,216,.1);border:1px solid rgba(21,101,216,.2);color:var(--a3);padding:6px 10px;border-radius:4px}
.note{background:rgba(240,165,0,.06);border:1px solid rgba(240,165,0,.2);border-radius:6px;padding:10px 13px;font-size:10px;color:var(--gold);line-height:1.7}
.cbadge{display:inline-flex;align-items:center;gap:5px;font-size:9.5px;background:rgba(0,200,112,.1);border:1px solid rgba(0,200,112,.25);color:var(--green);padding:3px 8px;border-radius:3px}
.cbadge::before{content:'';width:5px;height:5px;border-radius:50%;background:var(--green);flex-shrink:0}
.spin{width:11px;height:11px;border-radius:50%;border:1.5px solid rgba(255,255,255,.2);border-top-color:#fff;animation:rot .6s linear infinite;flex-shrink:0}
@keyframes rot{to{transform:rotate(360deg)}}
::-webkit-scrollbar{width:4px;height:4px}
::-webkit-scrollbar-track{background:var(--bg)}
::-webkit-scrollbar-thumb{background:var(--border);border-radius:2px}
`;

// ── Tooltip component ─────────────────────────────────────────
function Tip({ text, children, above = false }) {
  return (
    <div className="tip-wrap">
      {children}
      <div className={`tip-box ${above ? "above" : ""}`}>
        <span style={{ marginRight: 6, opacity: .7 }}>💡</span>
        {text}
      </div>
      <div className="tip-dot" />
    </div>
  );
}

// ── SPREADSHEET SECTION COMPONENT ────────────────────────────
function SheetSection({ title, icon, cols, rows, onRowChange, onAddRow, onDeleteRow,
  stateNames, selectedRow, onSelectRow, sectionKey, outgoingMap }) {
  const [open, setOpen] = useState(true);
  return (
    <div className="sec">
      <div className="sec-header" onClick={()=>setOpen(o=>!o)}>
        <span className="sec-chevron" style={open?{transform:"rotate(90deg)"}:{}}>{icon} ▶</span>
        <span className="sec-title">{title}</span>
        <span className="sec-count">{rows.length} rows</span>
        <button className="sec-add" onClick={e=>{e.stopPropagation();onAddRow();}}>+ Add</button>
      </div>
      {open && (
        <table className="sheet-table">
          <thead>
            <tr>
              <th style={{width:20}}/>
              {cols.map(c=><th key={c.key} style={{width:c.w}}>{c.label}</th>)}
              <th style={{width:28}}/>
            </tr>
          </thead>
          <tbody>
            {rows.map((row,ri)=>{
              const isSelected = selectedRow?.sec===sectionKey && selectedRow?.idx===ri;
              const outgoing   = outgoingMap?.[row.name] || [];
              return (
                <>
                  <tr key={ri}
                    className={isSelected?"selected":""}
                    onClick={()=>onSelectRow && onSelectRow({sec:sectionKey, idx:ri, name:row.name||row.from})}
                    style={{cursor:"pointer"}}
                  >
                    {/* Row index / selection indicator */}
                    <td style={{width:20,padding:0}}>
                      <div style={{display:"flex",alignItems:"center",height:"100%",paddingLeft:2}}>
                        {isSelected
                          ? <div style={{width:3,height:24,background:"var(--a3)",borderRadius:2,marginRight:2}}/>
                          : <span className="row-idx">{ri+1}</span>
                        }
                      </div>
                    </td>
                    {cols.map(c=>(
                      <td key={c.key} onClick={e=>e.stopPropagation()}>
                        {c.type==="check" ? (
                          <div className="cell-check">
                            <input type="checkbox" checked={!!row[c.key]}
                              onChange={e=>onRowChange(ri,c.key,e.target.checked)}/>
                          </div>
                        ) : c.type==="select" ? (
                          <select className="cell-select" value={row[c.key]||""}
                            onChange={e=>onRowChange(ri,c.key,e.target.value)}>
                            <option value="">— select —</option>
                            {(stateNames||[]).map(n=><option key={n} value={n}>{n}</option>)}
                          </select>
                        ) : c.type==="typesel" ? (
                          <select className="cell-select" value={row[c.key]||"Text"}
                            onChange={e=>onRowChange(ri,c.key,e.target.value)}>
                            {["Text","Integer","Decimal","Date","Lookup","Boolean"].map(t=><option key={t}>{t}</option>)}
                          </select>
                        ) : (
                          <input className="cell-input" value={row[c.key]||""} placeholder={c.placeholder||""}
                            onChange={e=>onRowChange(ri,c.key,e.target.value)}/>
                        )}
                      </td>
                    ))}
                    <td style={{width:28}} onClick={e=>e.stopPropagation()}>
                      <button className="del-btn" onClick={()=>onDeleteRow(ri)}>✕</button>
                    </td>
                  </tr>
                  {/* Outgoing transitions row — shown when state row is selected */}
                  {isSelected && sectionKey==="states" && outgoing.length>0 && (
                    <tr key={`${ri}-out`} style={{background:"rgba(21,101,216,.06)"}}>
                      <td colSpan={cols.length+2} style={{padding:0}}>
                        <div className="trans-badges">
                          <span style={{fontSize:9,color:"var(--dim)",marginRight:4}}>→ outgoing:</span>
                          {outgoing.map((t,i)=>(
                            <span key={i} className="trans-badge">{t}</span>
                          ))}
                        </div>
                      </td>
                    </tr>
                  )}
                </>
              );
            })}
          </tbody>
        </table>
      )}
    </div>
  );
}

// ── Cacoo mock response — simulates real API XML parse ────────
const CACOO_MOCK = {
  diagramName: "Contract Lifecycle — Service Agreement",
  states: [
    { name:"Draft",              initial:true  },
    { name:"Under Review",       initial:false },
    { name:"Reviewed",           initial:false },
    { name:"Approve 50k",        initial:false },
    { name:"Approve High",       initial:false },
    { name:"Signed Internally",  initial:false },
    { name:"Sent to Customer",   initial:false },
    { name:"Signed by Customer", initial:false },
    { name:"About to Expire",    initial:false },
    { name:"Expired",            initial:false },
    { name:"Discarded",          initial:false },
  ],
  transitions: [
    { from:"Draft",              to:"Under Review"       },
    { from:"Under Review",       to:"Reviewed"           },
    { from:"Under Review",       to:"Draft"              },
    { from:"Reviewed",           to:"Approve 50k"        },
    { from:"Reviewed",           to:"Approve High"       },
    { from:"Approve 50k",        to:"Signed Internally"  },
    { from:"Approve High",       to:"Signed Internally"  },
    { from:"Signed Internally",  to:"Sent to Customer"   },
    { from:"Sent to Customer",   to:"Signed by Customer" },
    { from:"Signed by Customer", to:"About to Expire"    },
    { from:"About to Expire",    to:"Expired"            },
    { from:"Draft",              to:"Discarded"          },
    { from:"Under Review",       to:"Discarded"          },
    { from:"Reviewed",           to:"Discarded"          },
    { from:"Discarded",          to:"Draft"              },
  ],
};

// Simulate Cacoo API fetch with realistic delay + XML parse simulation
const simulateCacooFetch = async (diagramId, apiKey) => {
  // Simulate network + XML parse time
  await new Promise(r => setTimeout(r, 600));
  // Simulate API validation
  if (!diagramId.trim() || !apiKey.trim()) throw new Error("Diagram ID and API Key required");
  await new Promise(r => setTimeout(r, 900));
  // Return mock parsed data as if from:
  // GET https://cacoo.com/api/v1/diagrams/{id}/contents.xml
  // ?returnValues=position,textStyle
  return CACOO_MOCK;
};

// ── SCREEN 1 — SOW SPREADSHEET EDITOR ────────────────────────
function SowEditor({ onSave }) {
  const [sheet,       setSheet]       = useState(JSON.parse(JSON.stringify(DEFAULT_SHEET)));
  const [tab,         setTab]         = useState("diagram");
  const [flash,       setFlash]       = useState(false);
  const [resetFlash,  setResetFlash]  = useState(false);
  const [resetKey,    setResetKey]    = useState(0);
  const [derr,        setDerr]        = useState("");
  const [selectedRow, setSelectedRow] = useState({ sec:"states", idx:0, name:"Draft" });
  // Cacoo import
  const [inputMode,   setInputMode]   = useState("sheet"); // sheet | cacoo
  const [cacooId,     setCacooId]     = useState("");
  const [cacooKey,    setCacooKey]    = useState("");
  const [cacooStatus, setCacooStatus] = useState("idle"); // idle | fetching | done | error
  const [cacooMsg,    setCacooMsg]    = useState("");
  const dRef  = useRef(null);
  const rcRef = useRef(0);

  const wf = sheetToWorkflow(sheet);
  const stateNames = sheet.states.filter(s=>s.name.trim()).map(s=>s.name);

  // outgoing transitions map: stateName -> [to, ...]
  const outgoingMap = {};
  sheet.transitions.forEach(t => {
    if (!t.from||!t.to) return;
    if (!outgoingMap[t.from]) outgoingMap[t.from]=[];
    outgoingMap[t.from].push(t.to);
  });

  // Render diagram
  useEffect(()=>{
    if(tab!=="diagram") return;
    const code = toMermaid(wf);
    if(!code) return;
    let dead=false;
    (async()=>{
      const m = await loadMermaid();
      rcRef.current++;
      const id=`m${rcRef.current}`;
      try{
        const {svg} = await m.render(id,code);
        if(!dead&&dRef.current){
          dRef.current.innerHTML=svg;
          setDerr("");
          highlightNode(dRef.current, selectedRow?.name);
        }
      }catch{if(!dead)setDerr("Diagram error — check state names");}
    })();
    return ()=>{dead=true;};
  },[wf,tab]);

  // Re-highlight when selection changes
  useEffect(()=>{
    if(tab!=="diagram"||!dRef.current) return;
    highlightNode(dRef.current, selectedRow?.name);
  },[selectedRow, tab]);

  const highlightNode = (container, stateName) => {
    if(!container||!stateName) return;
    const svgEl = container.querySelector("svg");
    if(!svgEl) return;
    // Reset all
    svgEl.querySelectorAll(".node rect,.node circle,.node polygon").forEach(el=>{
      el.style.stroke=""; el.style.strokeWidth=""; el.style.filter="";
    });
    svgEl.querySelectorAll(".node").forEach(n=>{ n.style.filter=""; n.style.transition=""; });
    // Highlight matching
    const id = stateName.replace(/\s+/g,"_").replace(/[^a-zA-Z0-9_]/g,"");
    svgEl.querySelectorAll(".node").forEach(node=>{
      const label = node.querySelector(".nodeLabel, text, span");
      const text  = label?.textContent?.trim()||"";
      if(text===stateName || (node.id&&node.id.includes(id))){
        const shape = node.querySelector("rect,circle,polygon");
        if(shape){ shape.style.stroke="#4A9FFF"; shape.style.strokeWidth="2.5"; shape.style.transition="all .3s"; }
        node.style.filter="drop-shadow(0 0 7px rgba(74,159,255,.8))";
        node.style.transition="filter .3s";
      }
    });
  };

  const handleSelectRow = (sel) => {
    setSelectedRow(sel);
    if(tab!=="diagram") setTab("diagram");
  };

  const upd = (section,ri,key,val) => {
    setSheet(prev=>{
      const next={...prev,[section]:[...prev[section]]};
      next[section][ri]={...next[section][ri],[key]:val};
      return next;
    });
  };
  const add = (section,blank) => setSheet(p=>({...p,[section]:[...p[section],blank]}));
  const del = (section,ri)    => setSheet(p=>({...p,[section]:p[section].filter((_,i)=>i!==ri)}));
  const save  = ()=>{ onSave(wf); setFlash(true); setTimeout(()=>setFlash(false),1800); };

  const reset = () => {
    const fresh = JSON.parse(JSON.stringify(DEFAULT_SHEET));
    setSheet(fresh);
    setSelectedRow({ sec:"states", idx:0, name:"Draft" });
    setResetKey(k => k + 1);
    setResetFlash(true);
    setTimeout(() => setResetFlash(false), 1800);
  };
  const downloadJson = ()=>{
    const a=document.createElement("a");
    a.href=URL.createObjectURL(new Blob([JSON.stringify(wf,null,2)],{type:"application/json"}));
    a.download="workflow.json"; a.click();
  };

  // Cacoo import handler
  const fetchFromCacoo = async () => {
    setCacooStatus("fetching");
    setCacooMsg("Connecting to Cacoo API...");
    try {
      setCacooMsg("Fetching diagram contents...");
      const data = await simulateCacooFetch(cacooId, cacooKey);
      setCacooMsg("Parsing XML — extracting states and transitions...");
      await new Promise(r => setTimeout(r, 400));

      // Populate spreadsheet from Cacoo data
      // Proviso is now the source of truth
      setSheet(prev => ({
        ...prev,
        name:        data.diagramName,
        states:      data.states,
        transitions: data.transitions,
        // Keep existing users/properties/rules — Cacoo only provides workflow structure
      }));
      setResetKey(k => k + 1);
      setSelectedRow({ sec:"states", idx:0, name:data.states[0]?.name || "Draft" });
      setCacooStatus("done");
      setCacooMsg(`✓ Imported ${data.states.length} states and ${data.transitions.length} transitions from Cacoo`);
      // Switch to spreadsheet view to show populated data
      setInputMode("sheet");
    } catch(e) {
      setCacooStatus("error");
      setCacooMsg(`⚠ ${e.message}`);
    }
  };

  const selInfo = selectedRow?.sec==="states" && selectedRow?.name;
  const selOutgoing = selInfo ? (outgoingMap[selectedRow.name]||[]) : [];

  return (
    <div className="ss-screen">
      <div className="ss-left">
        {/* ── Input mode tabs ── */}
        <div style={{
          display:"flex",alignItems:"center",gap:0,
          background:"var(--s2)",borderBottom:"1px solid var(--border)",
          padding:"8px 12px",flexShrink:0,
        }}>
          <div style={{display:"flex",background:"var(--s3)",border:"1px solid var(--border)",borderRadius:4,overflow:"hidden",marginRight:"auto"}}>
            <button
              onClick={()=>setInputMode("sheet")}
              style={{fontFamily:"var(--mono)",fontSize:9.5,padding:"4px 10px",border:"none",cursor:"pointer",transition:"all .15s",
                background:inputMode==="sheet"?"var(--accent)":"transparent",
                color:inputMode==="sheet"?"#fff":"var(--dim)",fontWeight:inputMode==="sheet"?"600":"400"
              }}>⬡ Spreadsheet</button>
            <button
              onClick={()=>setInputMode("cacoo")}
              style={{fontFamily:"var(--mono)",fontSize:9.5,padding:"4px 10px",border:"none",borderLeft:"1px solid var(--border)",cursor:"pointer",transition:"all .15s",
                background:inputMode==="cacoo"?"rgba(0,200,112,.2)":"transparent",
                color:inputMode==="cacoo"?"var(--green)":"var(--dim)",fontWeight:inputMode==="cacoo"?"600":"400"
              }}>⬡ Cacoo Import</button>
          </div>
          <div style={{display:"flex",gap:6}}>
            <button className={`xb ${resetFlash?"green":""}`} onClick={reset}>
              {resetFlash?"✓ Reset":"↺ Reset"}
            </button>
            <Tip text="Saves workflow.json and unlocks PRD & Ingest screens" above={true}>
              <button className={`xb ${flash?"green":"blue"}`} onClick={save}>
                {flash?"✓ Saved":"Save JSON"}
              </button>
            </Tip>
          </div>
        </div>

        {/* ── Cacoo import panel ── */}
        {inputMode==="cacoo" && (
          <div style={{
            background:"var(--s1)",borderBottom:"1px solid var(--border)",
            padding:"16px 16px",flexShrink:0,
          }}>
            {/* Header */}
            <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}>
              <div style={{width:8,height:8,borderRadius:"50%",background:"var(--green)",flexShrink:0}}/>
              <span style={{fontSize:10,fontWeight:700,color:"var(--green)",letterSpacing:"1px",textTransform:"uppercase"}}>
                Cacoo API Import
              </span>
              <span style={{fontSize:9,color:"var(--dim)",marginLeft:"auto"}}>
                DEMO — Simulated response
              </span>
            </div>

            {/* Fields */}
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:10}}>
              <div>
                <label style={{display:"block",fontSize:8.5,color:"var(--mid)",letterSpacing:"1px",textTransform:"uppercase",marginBottom:4}}>
                  Diagram ID
                </label>
                <input
                  style={{width:"100%",background:"var(--bg)",border:"1px solid var(--border)",borderRadius:4,padding:"7px 10px",fontFamily:"var(--mono)",fontSize:11,color:"var(--text)",outline:"none"}}
                  value={cacooId}
                  onChange={e=>setCacooId(e.target.value)}
                  placeholder="e.g. 00e77f4dc9973517"
                  onFocus={e=>e.target.style.borderColor="var(--a2)"}
                  onBlur={e=>e.target.style.borderColor="var(--border)"}
                />
              </div>
              <div>
                <label style={{display:"block",fontSize:8.5,color:"var(--mid)",letterSpacing:"1px",textTransform:"uppercase",marginBottom:4}}>
                  API Key
                </label>
                <input
                  style={{width:"100%",background:"var(--bg)",border:"1px solid var(--border)",borderRadius:4,padding:"7px 10px",fontFamily:"var(--mono)",fontSize:11,color:"var(--text)",outline:"none"}}
                  type="password"
                  value={cacooKey}
                  onChange={e=>setCacooKey(e.target.value)}
                  placeholder="Your Cacoo API key"
                  onFocus={e=>e.target.style.borderColor="var(--a2)"}
                  onBlur={e=>e.target.style.borderColor="var(--border)"}
                />
              </div>
            </div>

            {/* Fetch button */}
            <button
              onClick={fetchFromCacoo}
              disabled={cacooStatus==="fetching"}
              style={{
                width:"100%",padding:"9px",border:"none",borderRadius:4,
                fontFamily:"var(--mono)",fontSize:11,fontWeight:600,cursor:"pointer",
                transition:"all .15s",
                background:cacooStatus==="done"?"rgba(0,200,112,.15)":
                           cacooStatus==="error"?"rgba(255,61,90,.15)":"var(--accent)",
                border:`1px solid ${cacooStatus==="done"?"var(--green)":cacooStatus==="error"?"var(--red)":"var(--accent)"}`,
                color:cacooStatus==="done"?"var(--green)":cacooStatus==="error"?"var(--red)":"#fff",
                display:"flex",alignItems:"center",justifyContent:"center",gap:8,
                opacity:cacooStatus==="fetching"?.7:1,
              }}
            >
              {cacooStatus==="fetching"
                ? <><div className="spin" style={{borderTopColor:"#fff"}}/>Fetching from Cacoo...</>
                : cacooStatus==="done"
                ? "✓ Imported — Fetch Again"
                : "→ Fetch Diagram from Cacoo"
              }
            </button>

            {/* Status message */}
            {cacooMsg && (
              <div style={{
                marginTop:8,fontSize:10,lineHeight:1.6,
                color:cacooStatus==="error"?"var(--red)":cacooStatus==="done"?"var(--green)":"var(--mid)",
                padding:"6px 10px",background:"var(--bg)",borderRadius:3,
                border:`1px solid ${cacooStatus==="error"?"rgba(255,61,90,.2)":cacooStatus==="done"?"rgba(0,200,112,.2)":"var(--border)"}`,
              }}>
                {cacooMsg}
              </div>
            )}

            {/* Info note */}
            <div style={{marginTop:10,fontSize:9,color:"var(--dim)",lineHeight:1.7,borderTop:"1px solid var(--border)",paddingTop:8}}>
              Calls <span style={{color:"var(--a3)",fontFamily:"var(--mono)"}}>GET /api/v1/diagrams/{"{"}{"{id}"}{"}"}}/contents.xml</span>
              <br/>Parses groups+text → states · lines+arrows → transitions
              <br/>Once imported — <span style={{color:"var(--text)"}}>Proviso is the source of truth</span>
            </div>
          </div>
        )}

        <div className="sheet-body" key={resetKey}>
          <div className="proj-row">
            <span className="proj-label">Project name</span>
            <input className="proj-input" value={sheet.name}
              onChange={e=>setSheet(p=>({...p,name:e.target.value}))} placeholder="Enter project name"/>
          </div>
          <div className="proj-row">
            <span className="proj-label">Description</span>
            <input className="proj-input" value={sheet.description}
              onChange={e=>setSheet(p=>({...p,description:e.target.value}))} placeholder="Brief description"/>
          </div>
          <SheetSection title="States" icon="⬡" sectionKey="states"
            cols={[{key:"name",label:"State Name",w:"auto",placeholder:"e.g. Draft"},{key:"initial",label:"Initial",w:70,type:"check"}]}
            rows={sheet.states} selectedRow={selectedRow} onSelectRow={handleSelectRow}
            outgoingMap={outgoingMap}
            onRowChange={(ri,k,v)=>upd("states",ri,k,v)}
            onAddRow={()=>add("states",{name:"",initial:false})} onDeleteRow={ri=>del("states",ri)}/>
          <SheetSection title="Transitions" icon="→" sectionKey="transitions"
            cols={[{key:"from",label:"From",w:"50%",type:"select"},{key:"to",label:"To",w:"50%",type:"select"}]}
            rows={sheet.transitions} stateNames={stateNames} selectedRow={selectedRow} onSelectRow={handleSelectRow}
            onRowChange={(ri,k,v)=>upd("transitions",ri,k,v)}
            onAddRow={()=>add("transitions",{from:"",to:""})} onDeleteRow={ri=>del("transitions",ri)}/>
          <SheetSection title="Users" icon="👤" sectionKey="users"
            cols={[{key:"name",label:"Name",w:"25%",placeholder:"Full name"},{key:"role",label:"Role",w:"25%",placeholder:"e.g. CEO"},{key:"email",label:"Email",w:"35%",placeholder:"user@company.com"},{key:"isCM",label:"CM",w:40,type:"check"}]}
            rows={sheet.users} selectedRow={selectedRow} onSelectRow={handleSelectRow}
            onRowChange={(ri,k,v)=>upd("users",ri,k,v)}
            onAddRow={()=>add("users",{name:"",role:"",email:"",isCM:false})} onDeleteRow={ri=>del("users",ri)}/>
          <SheetSection title="Properties" icon="≡" sectionKey="properties"
            cols={[{key:"name",label:"Field Name",w:"40%",placeholder:"e.g. Contract Value"},{key:"type",label:"Type",w:"30%",type:"typesel"},{key:"required",label:"Required",w:60,type:"check"}]}
            rows={sheet.properties} selectedRow={selectedRow} onSelectRow={handleSelectRow}
            onRowChange={(ri,k,v)=>upd("properties",ri,k,v)}
            onAddRow={()=>add("properties",{name:"",type:"Text",required:false})} onDeleteRow={ri=>del("properties",ri)}/>
          <SheetSection title="Business Rules" icon="§" sectionKey="rules"
            cols={[{key:"text",label:"Rule",w:"100%",placeholder:"e.g. Only managers can approve"}]}
            rows={sheet.rules} selectedRow={selectedRow} onSelectRow={handleSelectRow}
            onRowChange={(ri,k,v)=>upd("rules",ri,k,v)}
            onAddRow={()=>add("rules",{text:""})} onDeleteRow={ri=>del("rules",ri)}/>
        </div>
      </div>

      <div className="ss-right">
        <div className="d-head">
          <span className="ss-headlbl">
            {tab==="diagram"
              ? selInfo ? `Diagram — ${selectedRow.name} selected` : "Live Workflow Diagram"
              : "workflow.json"}
          </span>
          <div style={{display:"flex",gap:6,alignItems:"center"}}>
            {/* Selected state badge with outgoing count */}
            {tab==="diagram" && selInfo && (
              <div style={{fontSize:9,background:"rgba(74,159,255,.1)",border:"1px solid rgba(74,159,255,.2)",color:"var(--a3)",padding:"2px 8px",borderRadius:3,display:"flex",alignItems:"center",gap:5}}>
                <span style={{width:6,height:6,borderRadius:"50%",background:"var(--a3)",display:"inline-block",animation:"tip-pulse 1.5s ease-in-out infinite"}}/>
                {selectedRow.name}
                {selOutgoing.length>0 && <span style={{color:"var(--dim)"}}>→ {selOutgoing.length} out</span>}
              </div>
            )}
            <div className="tab-row">
              <button className={`tab ${tab==="diagram"?"on":""}`} onClick={()=>setTab("diagram")}>Diagram</button>
              <button className={`tab ${tab==="json"?"on":""}`}    onClick={()=>setTab("json")}>JSON</button>
            </div>
            {tab==="json"&&<button className="xb" onClick={downloadJson}>↓ .json</button>}
          </div>
        </div>
        {tab==="diagram"?(
          <div className="d-body">
            {wf.states.length===0?(<div className="d-empty"><div className="d-empty-icon">⬡</div><div>Add states to see the diagram</div></div>)
              :derr?<div style={{color:"var(--red)",fontSize:11,padding:16}}>{derr}</div>
              :<div ref={dRef} style={{width:"100%"}}/>}
          </div>
        ):(
          <div className="json-body"><JV data={wf}/></div>
        )}
      </div>
    </div>
  );
}

// ── SCREEN 2 — PRD GENERATOR ──────────────────────────────────
function PrdGenerator({ savedWf }) {
  const [prd,       setPrd]       = useState("");
  const [generating,setGenerating]= useState(false);
  const [aiMode,    setAiMode]    = useState(false);
  const [status,    setStatus]    = useState("");
  const [view,      setView]      = useState("preview");

  const generate = async () => {
    if(!savedWf) return;
    setGenerating(true); setPrd(""); setStatus("");
    if(aiMode){
      setStatus("Calling Claude API...");
      try{
        const prompt=`Generate a comprehensive PRD in Markdown from this workflow specification.\nInclude: Overview, Users table, Workflow states+transitions, Properties, Business Rules, Test Cases, Build Estimate.\nStart with # [Project Name]. Output Markdown only.\n\nWorkflow JSON:\n${JSON.stringify(savedWf,null,2)}`;
        const resp=await fetch("https://api.anthropic.com/v1/messages",{
          method:"POST",headers:{"Content-Type":"application/json"},
          body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:1000,messages:[{role:"user",content:prompt}]})
        });
        const data=await resp.json();
        setPrd(data.content?.map(b=>b.text||"").join("")||"No response");
        setStatus("Generated with Claude AI ✦");
      }catch{
        await new Promise(r=>setTimeout(r,400));
        setPrd(generatePRD(savedWf));
        setStatus("API unavailable — generated locally ◈");
      }
    }else{
      setStatus("Extracting requirements...");
      await new Promise(r=>setTimeout(r,280));
      setStatus("Running NLP parser...");
      await new Promise(r=>setTimeout(r,320));
      setPrd(generatePRD(savedWf));
      setStatus("Generated locally ◈");
    }
    setGenerating(false);
  };

  const download=()=>{
    if(!prd)return;
    const a=document.createElement("a");
    a.href=URL.createObjectURL(new Blob([prd],{type:"text/markdown"}));
    a.download=`${savedWf?.name||"prd"}.md`;a.click();
  };

  return(
    <div className="prd-screen">
      {/* Left — controls */}
      <div className="prd-left">
        <div className="ss-head">
          <span className="ss-headlbl">PRD Generator</span>
          <div className="ss-acts">
            {/* Segmented toggle */}
            <div style={{display:"flex",background:"var(--s3)",border:"1px solid var(--border)",borderRadius:4,overflow:"hidden"}}>
              <button onClick={()=>setAiMode(false)} style={{fontFamily:"var(--mono)",fontSize:9.5,padding:"4px 9px",border:"none",cursor:"pointer",transition:"all .15s",background:!aiMode?"var(--accent)":"transparent",color:!aiMode?"#fff":"var(--dim)",fontWeight:!aiMode?"600":"400"}}>◈ NLP</button>
              <button onClick={()=>setAiMode(true)}  style={{fontFamily:"var(--mono)",fontSize:9.5,padding:"4px 9px",border:"none",borderLeft:"1px solid var(--border)",cursor:"pointer",transition:"all .15s",background:aiMode?"rgba(124,92,252,.3)":"transparent",color:aiMode?"#A78BFA":"var(--dim)",fontWeight:aiMode?"600":"400"}}>✦ AI</button>
            </div>
            <Tip text="Click to generate your PRD document" above={true}>
              <button className={`xb blue prd-btn`} onClick={generate} disabled={!savedWf||generating}>
                {generating?<><div className="spin" style={{borderTopColor:"#fff"}}/>Generating...</>:"Generate PRD"}
              </button>
            </Tip>
          </div>
        </div>

        <div style={{flex:1,overflow:"auto",padding:"14px 16px",fontSize:11,lineHeight:1.8}}>
          {!savedWf?(
            <div style={{color:"var(--dim)",padding:"20px 0",lineHeight:1.9}}>
              <div style={{color:"var(--gold)",marginBottom:8}}>⚠ No workflow loaded</div>
              Go to SOW Editor → fill in the spreadsheet → click Save JSON.
            </div>
          ):(
            <>
              <div style={{marginBottom:14}}>
                <div style={{fontSize:9,color:"var(--mid)",letterSpacing:"1px",textTransform:"uppercase",marginBottom:5}}>Loaded workflow</div>
                <div style={{color:"var(--text)",fontWeight:600}}>{savedWf.name||"Unnamed"}</div>
                <div style={{color:"var(--mid)",fontSize:10,marginTop:3}}>
                  {savedWf.states.length} states · {savedWf.transitions.length} transitions · {savedWf.users.length} users · {savedWf.properties.length} properties · {savedWf.rules.length} rules
                </div>
              </div>

              {/* Mode cards side by side */}
              <div className="mode-cards">
                <div className={`mode-card nlp ${aiMode?"inactive":""}`} onClick={()=>setAiMode(false)}>
                  <div className="mode-card-title">
                    ◈ Local NLP
                    {!aiMode&&<span className="mode-active-badge">ACTIVE</span>}
                  </div>
                  <div className="mode-card-body">Regex + pattern matching<br/>100% offline · instant</div>
                </div>
                <div className={`mode-card ai ${!aiMode?"inactive":""}`} onClick={()=>setAiMode(true)}>
                  <div className="mode-card-title">
                    ✦ AI Enhanced
                    {aiMode&&<span className="mode-active-badge">ACTIVE</span>}
                  </div>
                  <div className="mode-card-body">Claude API · richer output<br/>Handles complex prose</div>
                </div>
              </div>

              {status&&(
                <div style={{fontSize:10,color:aiMode?"#A78BFA":"var(--green)",marginBottom:8,display:"flex",alignItems:"center",gap:6}}>
                  <span>{generating?"⏳":"✓"}</span><span>{status}</span>
                </div>
              )}
              {generating&&(
                <div style={{display:"flex",alignItems:"center",gap:8,color:"var(--mid)",fontSize:11,padding:"8px 0"}}>
                  <div className="spin" style={{borderTopColor:aiMode?"#A78BFA":"var(--a3)"}}/>
                  {aiMode?"Claude is generating your PRD...":"Parsing requirements locally..."}
                </div>
              )}
              {prd&&!generating&&(
                <div style={{display:"flex",gap:8,marginTop:8}}>
                  <button className="xb blue" onClick={download}>↓ Download .md</button>
                  <button className="xb" onClick={()=>setView(v=>v==="preview"?"raw":"preview")}>
                    {view==="preview"?"Raw MD":"Preview"}
                  </button>
                </div>
              )}
            </>
          )}
        </div>
      </div>

      {/* Right — preview */}
      <div className="ss-right">
        <div className="d-head">
          <span className="ss-headlbl">{prd?(view==="preview"?"PRD Preview":"Raw Markdown"):"Preview"}</span>
          {prd&&(
            <div className="tab-row">
              <button className={`tab ${view==="preview"?"on":""}`} onClick={()=>setView("preview")}>Preview</button>
              <button className={`tab ${view==="raw"?"on":""}`}     onClick={()=>setView("raw")}>Raw</button>
            </div>
          )}
        </div>

        {!prd?(
          <div className="prd-empty">
            <div className="prd-empty-icon">📋</div>
            {savedWf?(
              <div className="hint-wrap">
                <div className="hint-ring-wrap">
                  <div className="hint-ring"/><div className="hint-ring"/><div className="hint-ring"/>
                </div>
                <div className="hint-label-row">
                  <span className="hint-arrow-txt">←</span>
                  <span className="hint-lbl">Generate PRD</span>
                </div>
                <div className="hint-sub">Click the button on the left to create your document</div>
                {/* Mode indicator — no hand icon */}
                <div style={{marginTop:8,padding:"5px 12px",background:"rgba(74,159,255,.06)",border:"1px solid rgba(74,159,255,.12)",borderRadius:20,fontSize:10,color:"var(--mid)",display:"flex",gap:8,alignItems:"center"}}>
                  <span style={{color:!aiMode?"var(--a3)":"var(--dim)",fontWeight:!aiMode?"700":"400",opacity:aiMode?.4:1}}>◈ Local NLP</span>
                  <span style={{color:"var(--border)"}}>|</span>
                  <span style={{color:aiMode?"#A78BFA":"var(--dim)",fontWeight:aiMode?"700":"400",opacity:!aiMode?.4:1}}>✦ AI-enhanced</span>
                </div>
              </div>
            ):(
              <div>No workflow loaded<br/><span style={{fontSize:10,color:"var(--dim)"}}>Complete the SOW Editor first</span></div>
            )}
          </div>
        ):view==="preview"?(
          <div className="prd-preview"><MD src={prd}/></div>
        ):(
          <div className="json-body"><pre style={{fontFamily:"JetBrains Mono,monospace",fontSize:10.5,lineHeight:1.7,color:"var(--text)",whiteSpace:"pre-wrap"}}>{prd}</pre></div>
        )}
      </div>
    </div>
  );
}

// ── SCREEN 3 — INGEST ─────────────────────────────────────────
function IngestWorkflow({ savedWf }) {
  const [server,   setServer]   = useState("localhost");
  const [vault,    setVault]    = useState("");
  const [user,     setUser]     = useState("admin");
  const [pass,     setPass]     = useState("");
  const [conning,  setConning]  = useState(false);
  const [connected,setConnected]= useState(false);
  const [status,   setStatus]   = useState("idle");
  const [logs,     setLogs]     = useState([]);
  const lRef=useRef(null);
  const wf=savedWf||{name:"",states:[],transitions:[]};
  useEffect(()=>{if(lRef.current)lRef.current.scrollTop=lRef.current.scrollHeight;},[logs]);
  const ts=()=>new Date().toLocaleTimeString("en-CA",{hour12:false});
  const log=(msg,type="info")=>setLogs(p=>[...p,{t:ts(),msg,type}]);
  const connect=async()=>{
    if(!server||!vault||!user)return;
    setConning(true);await new Promise(r=>setTimeout(r,1100));
    setConnected(true);setConning(false);
    log(`Connected: ${server}`,"ok");log(`Vault: ${vault}`,"info");log(`User: ${user}`,"ok");
  };
  const ingest=async()=>{
    if(!connected||!wf.states.length)return;
    setStatus("running");setLogs([]);
    log("Initialising M-Files COM API — server mode","info");
    await new Promise(r=>setTimeout(r,500));
    log("MFilesAPI.MFilesServerApplication — connected","ok");
    await new Promise(r=>setTimeout(r,400));
    log(`Creating workflow: "${wf.name||"Unnamed"}"`,"info");
    await new Promise(r=>setTimeout(r,600));
    log("  VaultWorkflowOperations.AddWorkflowAdmin() — success","ok");
    log(`Adding ${wf.states.length} states...`,"info");
    for(const s of wf.states){await new Promise(r=>setTimeout(r,100));log(`  ✓ State: "${s.name}"${s.initial?" [INITIAL]":""}`, "ok");}
    await new Promise(r=>setTimeout(r,350));
    log(`Adding ${wf.transitions.length} transitions...`,"info");
    for(const t of wf.transitions){await new Promise(r=>setTimeout(r,75));log(`  ✓ ${t.from} → ${t.to}`,"ok");}
    await new Promise(r=>setTimeout(r,450));
    log("VaultWorkflowOperations.UpdateWorkflowAdmin() — committed ✓","ok");
    log("","info");log("✓ Phase 1 complete — workflow skeleton ingested","ok");
    log("  No conditions · No permissions applied","warn");
    log("  → Open M-Files Admin to add rules (Phase 2)","warn");
    setStatus("done");
  };
  return(
    <div className="ingest-screen">
      {!savedWf&&<div className="note">⚠ No workflow loaded — complete the SOW Editor and click Save JSON first.</div>}
      <div className="stats">
        <div className="stat"><div className={`sv ${wf.name?"":"off"}`}>{wf.name?1:0}</div><div className="sl">Workflow</div></div>
        <div className="stat"><div className={`sv ${wf.states.length?"":"off"}`}>{wf.states.length||"—"}</div><div className="sl">States</div></div>
        <div className="stat"><div className={`sv ${wf.transitions.length?"":"off"}`}>{wf.transitions.length||"—"}</div><div className="sl">Transitions</div></div>
        <div className="stat"><div className="sv off">Ph.2</div><div className="sl">Rules</div></div>
      </div>
      <div className="card">
        <div className="card-head"><span className="card-title">M-Files Vault — COM API Connection</span>{connected&&<span className="cbadge">Connected</span>}</div>
        <div className="card-body">
          <div className="fields">
            <div><label className="fl">Server</label><input className="fi" value={server} onChange={e=>{setServer(e.target.value);setConnected(false)}} placeholder="localhost" disabled={conning}/></div>
            <div><label className="fl">Username</label><input className="fi" value={user} onChange={e=>{setUser(e.target.value);setConnected(false)}} placeholder="admin" disabled={conning}/></div>
            <div className="ff"><label className="fl">Vault GUID</label><input className="fi" value={vault} onChange={e=>{setVault(e.target.value);setConnected(false)}} placeholder="{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}" disabled={conning}/></div>
            <div><label className="fl">Password</label><input className="fi" type="password" value={pass} onChange={e=>{setPass(e.target.value);setConnected(false)}} placeholder="••••••••" disabled={conning}/></div>
            <div style={{display:"flex",alignItems:"flex-end"}}>
              <button className="xb blue" style={{width:"100%",padding:"8px 0",fontSize:11}} onClick={connect} disabled={conning||connected||!server||!vault||!user}>
                {conning?<><div className="spin" style={{width:10,height:10,marginRight:6}}/>Connecting...</>:connected?"✓ Connected":"Connect"}
              </button>
            </div>
          </div>
          <div style={{marginTop:10,fontSize:9,color:"var(--dim)",lineHeight:1.8}}>COM API requires M-Files client installed on this Windows machine · Flask API on localhost:5000</div>
        </div>
      </div>
      <button className={`big-btn ${status==="done"?"done":""}`} onClick={ingest} disabled={!connected||!wf.states.length||status==="running"}>
        {status==="running"?<><div className="spin"/>Ingesting workflow into vault...</>:status==="done"?"✓ Ingested — Run Again":"→ Ingest Workflow into M-Files Vault"}
      </button>
      <div className="log" ref={lRef}>
        {logs.length===0?<span style={{color:"var(--dim)"}}>{connected?"— ready — click Ingest to push workflow into vault":"— connect to vault first —"}</span>
          :logs.map((l,i)=><div key={i} className="ll"><span className="lt">{l.t}</span><span className={`l${l.type}`}>{l.msg}</span></div>)}
      </div>
      {status==="done"&&(
        <div className="result-row">
          <div className="ri">✅</div>
          <div><div className="rt">"{wf.name}" ingested into vault</div><div className="rs">{wf.states.length} states · {wf.transitions.length} transitions · no rules</div></div>
          <div className="rp">Next step<br/><strong style={{color:"var(--a3)"}}>Open M-Files Admin</strong><br/>Add rules → Phase 2</div>
        </div>
      )}
    </div>
  );
}

// ── APP SHELL ─────────────────────────────────────────────────
const NAV_SCREENS = [
  {id:"sow",    num:"1", label:"SOW Editor",     sub:"Spreadsheet + Diagram"},
  {id:"prd",    num:"2", label:"Generate PRD",   sub:"NLP · AI-enhanced"    },
  {id:"ingest", num:"3", label:"Ingest Workflow", sub:"COM API → Vault"      },
];

export default function App() {
  const [screen,  setScreen]  = useState("sow");
  const [savedWf, setSavedWf] = useState(null);
  const [hasSaved,setHasSaved]= useState(false);

  const currentIdx = NAV_SCREENS.findIndex(n=>n.id===screen);

  const goUp   = () => { if(currentIdx>0)                         setScreen(NAV_SCREENS[currentIdx-1].id); };
  const goDown = () => { if(currentIdx<NAV_SCREENS.length-1)      setScreen(NAV_SCREENS[currentIdx+1].id); };

  const canGoUp   = currentIdx > 0;
  const canGoDown = currentIdx < NAV_SCREENS.length - 1;

  const TITLES = {
    sow:    "SOW Editor — Spreadsheet Input + Live Mermaid Diagram",
    prd:    "Generate PRD — Local NLP or AI-Enhanced via Claude",
    ingest: "Ingest Workflow — Connect to M-Files Vault & Push",
  };

  return(
    <>
      <style>{CSS}</style>
      <div className="shell">
        <div className="sb">
          <div className="sb-logo">
            <div className="sb-wm">provi<em>so</em></div>
            <div className="sb-tag">Workflow Ingestion · v0.1</div>
          </div>
          <nav className="sb-nav">
            {NAV_SCREENS.map(n=>{
              // Tooltip text per nav item
              const tipText = {
                sow:    !hasSaved ? "Fill the spreadsheet then click Save JSON" : "✓ workflow.json saved",
                prd:    !hasSaved ? "Save JSON in SOW Editor first" : "Click Generate PRD to create your document",
                ingest: !hasSaved ? "Complete SOW Editor first" : "Connect vault and click Ingest Workflow",
              }[n.id];

              return (
                <Tip key={n.id} text={tipText}>
                  <div className={`sb-item ${screen===n.id?"active":""} ${n.id==="sow"&&hasSaved?"done":""}`}
                    onClick={()=>setScreen(n.id)}
                    style={{width:"100%"}}
                  >
                    <div className="sb-num">{n.id==="sow"&&hasSaved?"✓":n.num}</div>
                    <div><div className="sb-lbl">{n.label}</div><div className="sb-sub">{n.sub}</div></div>
                  </div>
                </Tip>
              );
            })}
          </nav>
          <div className="sb-foot">
            <div><span className={`dot ${hasSaved?"on":""}`}/>{hasSaved?"workflow.json saved":"no workflow saved"}</div>
            {savedWf&&<div style={{color:"var(--mid)",fontSize:9,marginTop:3}}>{savedWf.name||"Unnamed"}<br/>{savedWf.states.length} states · {savedWf.transitions.length} tr.</div>}
            <div style={{marginTop:10,paddingTop:10,borderTop:"1px solid var(--border)",color:"var(--dim)",fontSize:9,lineHeight:1.8}}>Phase 1 · States + transitions<br/>No rules · No conditions</div>
          </div>
        </div>

        <div className="main">
          <div className="topbar">
            <span className="tb-title">{TITLES[screen]}</span>
            <span className="tb-pill">Phase 1 POC</span>
            {screen==="prd"&&<span className="tb-pill ai">✦ AI Available</span>}

            {/* Up/Down navigation arrows */}
            <div className="nav-hint">
              <span style={{fontSize:9,color:"var(--mid)"}}>
                {canGoUp   ? NAV_SCREENS[currentIdx-1].label : ""}
                {canGoDown ? NAV_SCREENS[currentIdx+1].label : ""}
              </span>
              <div className="nav-hint-arrow">
                <div className={`nav-arrow ${canGoUp?"active":""}`}
                  onClick={goUp}
                  title={canGoUp?`Go to ${NAV_SCREENS[currentIdx-1].label}`:"Already at first screen"}
                  style={{opacity:canGoUp?1:.25}}>▲</div>
                <div className={`nav-arrow ${canGoDown?"active":""}`}
                  onClick={goDown}
                  title={canGoDown?`Go to ${NAV_SCREENS[currentIdx+1].label}`:"Already at last screen"}
                  style={{opacity:canGoDown?1:.25}}>▼</div>
              </div>
            </div>
          </div>

          <div className="content">
            {screen==="sow"    && <SowEditor    onSave={wf=>{setSavedWf(wf);setHasSaved(true);}}/>}
            {screen==="prd"    && <PrdGenerator savedWf={savedWf}/>}
            {screen==="ingest" && <IngestWorkflow savedWf={savedWf}/>}
          </div>
        </div>
      </div>
    </>
  );
}
